### ISSUE TITLE
Salus is'ent showing up in integrations

### ISSUE THREAD

**Issue by jansejer** [jvitkauskas/homeassistant_salus#10]
Hi, Any idea why Salus dosent show up under configurations->integrations after making the install in HACS?

**Comment by jvitkauskas** [comment]
The readme was a bit outdated. You basically have to copy `custom_components` folder from this repository to `/config`

**Comment by jvitkauskas** [comment]
@jansejer did that solve your issue?

**Comment by jansejer** [comment]
yes it works absolutely perfect now. thanks

**Comment by jvitkauskas** [comment]
Thanks. Closing this.
