### ISSUE TITLE
Unavailable entries after reboot. 

### ISSUE THREAD

**Issue by bse4792** [jvitkauskas/homeassistant_salus#11]
Hi I'm facing a weird problem.

All is working well and fine when I install via hacs.
I add the integration give key and ip, all entries comes and changeable. 

But when I restart HA, then all entries becomes unavailable. 
Then I can remove and add integration and then it's working fine. 

I have tried reinstall via hacs, but nothing seems to work. 

Kindly Daniel

**Comment by jvitkauskas** [comment]
Can you see any errors in the logs?

**Comment by bse4792** [comment]
Hi I just removed integration now and reintegrated it to be sure it was OK and working. 

Was working perfectly before reboot but after not. 

![Screenshot_20210219-175934](https://user-images.githubusercontent.com/29598723/108536224-79658500-72dc-11eb-9d2e-4af26c24bca3.jpg)
Here is the log after normal reboot as you described never do it in other ways.

**Comment by bse4792** [comment]
It also come with this error

![Screenshot_20210219-180631](https://user-images.githubusercontent.com/29598723/108537030-6acb9d80-72dd-11eb-9b82-757b09ecb9b8.jpg)

**Comment by bse4792** [comment]
Here is proof it's working prereboot

![Screenshot_20210219-205003](https://user-images.githubusercontent.com/29598723/108554433-5e067400-72f4-11eb-831b-511f7137ef4b.jpg)
![Screenshot_20210219-205018](https://user-images.githubusercontent.com/29598723/108554445-62cb2800-72f4-11eb-96ba-c8f6a7605404.jpg)
![Screenshot_20210219-205046](https://user-images.githubusercontent.com/29598723/108554458-66f74580-72f4-11eb-8760-80a064e31407.jpg)

**Comment by jvitkauskas** [comment]
Are you running homeassistant on a raspberry pi (which version) or on a PC or in a VM?

**Comment by bse4792** [comment]
VM on esxi 6.0 with image from home assistant. So obviously wired ethernet. 

wired ethernet on uge600 but WiFi credentials are added

Configuration -> server control -> reboot

**Comment by bse4792** [comment]
![Screenshot_20210219-221506](https://user-images.githubusercontent.com/29598723/108562305-f22a0880-72ff-11eb-8555-347861cf3507.jpg)

**Comment by marithpl** [comment]
I've got the same problem. Usually after fresh start of Home Assistant the Salus Thermostats are unavailable.

`2021-02-24 11:15:32 ERROR (MainThread) [custom_components.salus] Authentication error: check if you have specified gateway's EUID correctly.
`

Usually restart HA from UI helps, but not always.

My config is:
Home Assistant installed via Docker on Synology NAS
Salus Gateway conntected via Wi-Fi with strong signal

**Comment by jvitkauskas** [comment]
Unfortunately I can't reproduce this, think I'll do a 3 time connection retry. Maybe it would help.

**Comment by jvitkauskas** [comment]
I've added a simple 3 time retry with 3 second delay between retries.

**Comment by jvitkauskas** [comment]
@bse4792 @marithpl have you tried new version? Did it solve your problems?

**Comment by bse4792** [comment]
Hi @jvitkauskas yes i have tried, but it did not resolve the problem.

i'm considering trying a new HA install just to test, if that is my problem

**Comment by jvitkauskas** [comment]
It sucks that I cannot reproduce this myself. Maybe one of you have access to a smart(er) switch with port mirroring and could set up wireshark to see how many connection attempts/requests are being sent to gateway and of they timeout or whatnot.

**Comment by bse4792** [comment]
i'm getting a dream mashine some time this week and will resetup my wifi/network completely

if you could help me with tcp trafic dump then it would be helpful.

as of now i'm using pfsense in VM and i'm expecting that to cause some problems.
can you send private massage then we can take this a bit more secure

**Comment by marithpl** [comment]
Recently I didn't observe this problem.

**Comment by bse4792** [comment]
seams to be working now
