### ISSUE TITLE
Bug with PS600 

### ISSUE THREAD

**Issue by George-andrew** [jvitkauskas/homeassistant_salus#12]
Dear Julius, 

I found a bug with my PS600,
in HA shows two devices like the temperature sensor and binary sensor with the same name  

Below in attachment my screenshot :  
![image](https://user-images.githubusercontent.com/67461821/108077744-28038e80-706d-11eb-89de-be8c6ebfb7c8.png)
![image](https://user-images.githubusercontent.com/67461821/108077822-41a4d600-706d-11eb-98a3-7aebdd37b3c5.png)

``

**Comment by jvitkauskas** [comment]
Can you check if binary sensor gets activated if you remove back cover (not the front one which contains battery)?

**Comment by George-andrew** [comment]
@jvitkauskas OK, many thanks for your answer 
But if you have will anytime, please hide this  entity in homeassistant UI
