### ISSUE TITLE
Home Assistant 2022.3.0 breaking change

### ISSUE THREAD

**Issue by mindvisionro** [jvitkauskas/homeassistant_salus#29]
After the update, the integration does not start.

https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by willhaggan** [comment]
Hi same issue here.

Logger: homeassistant.util.package
Source: util/package.py:99
First occurred: 07:41:43 (3 occurrences)
Last logged: 07:41:59

Unable to install package pyit600==0.3.2: ERROR: Cannot install pyit600==0.3.2 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Diomet** [comment]
Same here:

Logger: homeassistant.setup
Source: setup.py:155
First occurred: 12:10:24 (1 occurrences)
Last logged: 12:10:24

Setup failed for salus: Requirements for salus not found: ['pyit600==0.3.2'].

**Comment by mobopx** [comment]
on 2022.3.1 it doesn't work either

**Comment by mobopx** [comment]
i found such a tip, but i didn/t test it

https://community.home-assistant.io/t/2022-3-select-and-play-media/398201/192?u=mobopx

**Comment by Eugen66-cmd** [comment]
Hi same issue here.

**Comment by SemyonSV** [comment]
On 2022.3.1 it doesn't work

**Comment by jvitkauskas** [comment]
Can you try 0.4.0?

**Comment by Eugen66-cmd** [comment]
I reverted to 2022.2.7 because I can't use it at all. Not even delete it
from integrations, but if you think you have fixed it I'll try again ...

În vin., 4 mar. 2022 la 23:47, Julius Vitkauskas ***@***.***>
a scris:

**Comment by Eugen66-cmd** [comment]
Should I uninstall it first?

În vin., 4 mar. 2022 la 23:57, Eugen Ginta ***@***.***> a scris:

**Comment by Eugen66-cmd** [comment]
OK, done. Just copied new files ad restart.
Works for me, no more errors.

În sâm., 5 mar. 2022 la 00:01, Eugen Ginta ***@***.***> a scris:

**Comment by willhaggan** [comment]
Hi there yes the latest update fixes the issue.
Thanks for the quick response.

**Comment by mindvisionro** [comment]
Works with the latest update. Thanks for the quick fix.
