### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by jvitkauskas** [jvitkauskas/homeassistant_salus#44]
I am no longer developing this integration and therefore I am seeking someone who is willing to maintain it. Please contact me if you are interested.

**Comment by YashoEsparta** [comment]
Hi, i am interested in realize one change in SQ610 device for support HVAC_MODE_COOL mode, is possible?

**Comment by jvitkauskas** [comment]
I have transferred ownership of this repo and pyit600 repo to @epoplavskis. Edgaras has volunteered to continue the development of this project.
