### ISSUE TITLE
Missing follow schedule button from thermostat card.

### ISSUE THREAD

**Issue by albei** [jvitkauskas/homeassistant_salus#6]
Something is not quite complete. I tested both homeassistant_salus gits, yours and konradb3's. In Konradsb3's the follow schedule button exists in your doesnt. I only see the heat and the off button. It a little beyond me, cant manage to find the cause. Gonna still look for it comparing the code.

**Comment by albei** [comment]
I found what is missing, gonna do a patch later today together with another small change I made for temp display.

**Comment by jvitkauskas** [comment]
Fixed in pyit600. Thanks.
